
export const productsData = [
    {
      productId: "1",
      productTag: "New",
      productName: "Fresh Tomato",
      productImg: "product-1.jpg",
      productPrice: "$29.00",
      productDiscountPrice: "$19.00",
      category: "Vegetable",
    },
    {
      productId: "2",
      productTag: "New",
      productName: "Fresh Apple",
      productImg: "product-2.jpg",
      productPrice: "$29.00",
      productDiscountPrice: "$19.00",
      category: "Fruits",
    },
    {
      productId: "3",
      productTag: "New",
      productName: "Fresh Banana",
      productImg: "product-3.jpg",
      productPrice: "$29.00",
      productDiscountPrice: "$19.00",
      category: "Fruits",
    },
    {
      productId: "4",
      productTag: "New",
      productName: "Fresh Carrot",
      productImg: "product-4.jpg",
      productPrice: "$29.00",
      productDiscountPrice: "$19.00",
      category: "Vegetable",
    },
    {
      productId: "5",
      productTag: "New",
      productName: "Fresh Orange",
      productImg: "product-5.jpg",
      productPrice: "$29.00",
      productDiscountPrice: "$19.00",
      category: "Fruits",
    },
    {
      productId: "6",
      productTag: "New",
      productName: "Fresh Lettuce",
      productImg: "product-6.jpg",
      productPrice: "$29.00",
      productDiscountPrice: "$19.00",
      category: "Vegetable",
    },
  ];
